import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavTop from "./components/Nav-top";
import NavMid from "./components/Nav-Mid";
import NavLinks from "./components/Nav-Links";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavTop/>
        <NavMid/>
        <NavLinks/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
